apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: V3BTZWN1cmUyMDI2IVJhbmQjSzhz
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: d29yZHByZXNzdXNlcg==
  MYSQL_PASSWORD: V29yZFByMjAyNiNQYXNz
